apiVersion: v1
kind: Pod
metadata:
  name: annotationpod
  annotations:
    owner: "Ozgur OZTURK"
    notification-email: "admin@k8sfundamentals.com"
    releasedate: "01.01.2021"
    nginx.ingress.kubernetes.io/force-ssl-redirect: "true"
spec:
  containers:
  - name: annotationcontainer
    image: nginx
    ports:
    - containerPort: 80

    # annotations → sadece açıklama ve metadata tutar, seçim için kullanılmaz. 
    # labels → seçim/filtreleme için kullanılır (kubectl get pods -l app=frontend).